/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRuleAccess().getAlternatives_2(), "rule__Rule__Alternatives_2");
			builder.put(grammarAccess.getVariantAccess().getAlternatives(), "rule__Variant__Alternatives");
			builder.put(grammarAccess.getCardsEffectAccess().getAlternatives_2(), "rule__CardsEffect__Alternatives_2");
			builder.put(grammarAccess.getCumulatingMalusAccess().getAlternatives_2(), "rule__CumulatingMalus__Alternatives_2");
			builder.put(grammarAccess.getUnoAccess().getGroup(), "rule__Uno__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getOriginalAccess().getGroup(), "rule__Original__Group__0");
			builder.put(grammarAccess.getCardsEffectAccess().getGroup(), "rule__CardsEffect__Group__0");
			builder.put(grammarAccess.getCardsEffectAccess().getGroup_2_0(), "rule__CardsEffect__Group_2_0__0");
			builder.put(grammarAccess.getCardsEffectAccess().getGroup_2_1(), "rule__CardsEffect__Group_2_1__0");
			builder.put(grammarAccess.getCardsEffectAccess().getGroup_2_2(), "rule__CardsEffect__Group_2_2__0");
			builder.put(grammarAccess.getCumulatingMalusAccess().getGroup(), "rule__CumulatingMalus__Group__0");
			builder.put(grammarAccess.getCumulatingMalusAccess().getGroup_2_0(), "rule__CumulatingMalus__Group_2_0__0");
			builder.put(grammarAccess.getCumulatingMalusAccess().getGroup_2_1(), "rule__CumulatingMalus__Group_2_1__0");
			builder.put(grammarAccess.getCumulatingMalusAccess().getGroup_2_2(), "rule__CumulatingMalus__Group_2_2__0");
			builder.put(grammarAccess.getHandsDownAccess().getGroup(), "rule__HandsDown__Group__0");
			builder.put(grammarAccess.getWithoutMalusAccess().getGroup(), "rule__WithoutMalus__Group__0");
			builder.put(grammarAccess.getUnoAccess().getGameAssignment_2(), "rule__Uno__GameAssignment_2");
			builder.put(grammarAccess.getUnoAccess().getRulesAssignment_4(), "rule__Uno__RulesAssignment_4");
			builder.put(grammarAccess.getRuleAccess().getVariantsAssignment_2_1(), "rule__Rule__VariantsAssignment_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
