/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uno</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Uno#getGame <em>Game</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Uno#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUno()
 * @model
 * @generated
 */
public interface Uno extends EObject
{
  /**
   * Returns the value of the '<em><b>Game</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game</em>' attribute.
   * @see #setGame(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUno_Game()
   * @model
   * @generated
   */
  String getGame();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Uno#getGame <em>Game</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Game</em>' attribute.
   * @see #getGame()
   * @generated
   */
  void setGame(String value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUno_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // Uno
